### ISSUE TITLE
Inconsistent handling of upper-cased sequences

### ISSUE THREAD

**Issue by GeoJGH** [JasperFx/weasel#100]
If someone use a sequence name containing an upper case letter, he will be able to run its app once and query the sequence successfully but it will fail on the next app launch.

[Code](https://github.com/JasperFx/weasel/blob/6b22dd7ea122c75605ad2d0e894781bf31698614/src/Weasel.Postgresql/Sequence.cs#L40C13-L40C13) to create the sequence does not add double quotes, so the identifier is converted to lower case.
When you query the nextval, the identifier is also not double-quoted so its lower case version is used and the sequence returns the desired value.

Next time you run your app, the [code](https://github.com/JasperFx/weasel/blob/6b22dd7ea122c75605ad2d0e894781bf31698614/src/Weasel.Postgresql/Sequence.cs#L58C10-L58C10) that looks if the sequence exists or not uses the identifier as-is, so containing an upper-case. There is no sequence under that name so the sequence is created again, using again the lower-cased name, which already exists.

Solutions: 
1) always double quote the sequence name
2) or lower-case the sequence name when looking if it already exists

PS: as reported in this [stackoverflow post](https://stackoverflow.com/questions/77071295/marten-using-sequences-add-new-sequence-fails-on-2nd-run/77072823#77072823)

**Comment by oskardudycz** [comment]
@GeoJGH, I added a solution for that in https://github.com/JasperFx/weasel/pull/103 and released in [6.2.0](https://github.com/JasperFx/weasel/releases/tag/6.2.0)

It should work now if you set `PostgresqlProvider.Instance.UseCaseSensitiveQualifiedNames` to `true`
