### ISSUE TITLE
Transient System.Text.RegularExpressions package vulnerability

### ISSUE THREAD

**Issue by baltie** [JasperFx/weasel#125]
The new `System.Data.Common@4.3.0` dependency in `Weasel.Core` adds a transient dependency on `System.Text.RegularExpressions@4.3.0` which has a high severity vulnerability. See https://github.com/advisories/GHSA-cmhx-cq75-c4mj.

As a workaround, I can add `System.Text.RegularExpressions` as a direct dependency, but it is not good to have vulnerable packages added transiently, at least not due to a recent change. 😄 

This is the change: https://github.com/JasperFx/weasel/commit/f74f7308a3fad5c9e2f11eb9148981b76e2704cf#diff-8fc294e21b8f18d4e1bc70eebda5148d0f41f96bcdb17361fae1c15fc240d8ddR20

**Comment by jeremydmiller** [comment]
@baltie Sounds like a helpful pull request!

**Comment by baltie** [comment]
Heh, all right, I'll have a look at it. 

I did investigate our exposure to this and determined that even if the GitHub dependency scanner decided it was harmful, the actual DLLs involved were the ones from .NET 8, not version 4.3.0. So, it was a false positive. Regardless, it would be nice if we could avoid it as both GitHub and the VS NuGet package manager throws up warnings about this transient dependency.

**Comment by zkingston-polly** [comment]
I am having the same issue. Thank you @baltie for the pull request!
