### ISSUE TITLE
Support FASTUPDATE on gin indexes

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/weasel#25]
Low priority.

**Comment by mysticmind** [comment]
Using `StorageParameters`, `FASTUPDATE` can added as below:
`index2.StorageParameters.Add("FASTUPDATE", "ON");`

This is already supported, closing the same.

**Comment by mysticmind** [comment]
Added unit test via https://github.com/JasperFx/weasel/commit/728a7bda5c967b54fbe6a7af580091d13c9fed3a
