### ISSUE TITLE
Schema validation fails if index has CAST(... as uuid) 

### ISSUE THREAD

**Issue by VilleHakli** [JasperFx/weasel#27]
When updating Marten to RC2, I came across problem with index schema validation. If in Marten document's index has guid, which is not duplicated, Marten generates cast into the index: `CREATE INDEX idx_people_data ON deltas.people USING btree (CAST(data ->> 'SomeGuid' as uuid));`

When current schema is fetched from database it is read as `CREATE INDEX idx_people_data ON deltas.people USING btree (((data ->> 'SomeGuid'))::uuid);` which will not match.

After `CanonicizeDdl` call, the definitions compared are `CREATE INDEX idx_people_data ON deltas.people USING btree CASTdata->>'SomeGuid' as uuid` and `CREATE INDEX idx_people_data ON deltas.people USING btree data->>'SomeGuid'::uuid`.

Here are two test cases for detecting_table_deltas.matching_index_ddl:
```csharp
yield return ("Jsonb property with cast", t => t.ModifyColumn("data").AddIndex(i => i.Columns = new[] {"CAST(data ->> 'SomeGuid' as uuid)"}));
yield return ("Jsonb property with cast + unique", t => t.ModifyColumn("data").AddIndex(i =>
{
    i.Columns = new[] {"CAST(data ->> 'SomeGuid' as uuid)"};
    i.IsUnique = true;
}));
```

**Comment by jeremydmiller** [comment]
@VilleHakli Sorry for the delay, just saw this. I'll take this soon before we go 4.0

**Comment by jeremydmiller** [comment]
I'm on this today.
