### ISSUE TITLE
Any plan to use Npgsql 7.0.0 ?

### ISSUE THREAD

**Issue by ronikurnia1** [JasperFx/weasel#72]
Any plan to use Npgsql 7.0.0 ?

**Comment by mysticmind** [comment]
@ronikurnia1 Oskar is looking at npgsql7, please await for updates in few weeks.

**Comment by ronikurnia1** [comment]
Thanks @mysticmind, I just found some issue with TypeMapping especially DateTimeOffset in C#

**Comment by jeremydmiller** [comment]
And this is done.
